version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo
    steps:
      - run:
          name: run tests
          command: |
            echo "Running tests"

  deploy:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo
    steps:
      - run:
          name: deploy app
          command: |
            echo "Deploying app"

workflows:
  build:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master

